import type * as Monaco from "monaco-editor";
import type { ThemeName } from "./theme-data";

export const monacoThemes: Record<
	ThemeName,
	Monaco.editor.IStandaloneThemeData
> = {
	"vscode-dark": {
		base: "vs-dark",
		inherit: true,
		rules: [
			{ token: "comment", foreground: "6A9955" },
			{ token: "keyword", foreground: "569CD6" },
			{ token: "string", foreground: "CE9178" },
			{ token: "number", foreground: "B5CEA8" },
			{ token: "type", foreground: "4EC9B0" },
			{ token: "function", foreground: "DCDCAA" },
			{ token: "variable", foreground: "9CDCFE" },
			{ token: "constant", foreground: "4FC1FF" },
		],
		colors: {
			"editor.background": "#1e1e1e",
			"editor.foreground": "#d4d4d4",
			"editorLineNumber.foreground": "#858585",
			"editorLineNumber.activeForeground": "#c6c6c6",
			"editor.selectionBackground": "#264f78",
			"editor.lineHighlightBackground": "#2a2d2e",
			"editorCursor.foreground": "#aeafad",
			"editorIndentGuide.background": "#404040",
			"editorIndentGuide.activeBackground": "#707070",
		},
	},
	"vscode-light": {
		base: "vs",
		inherit: true,
		rules: [
			{ token: "comment", foreground: "008000" },
			{ token: "keyword", foreground: "0000FF" },
			{ token: "string", foreground: "A31515" },
			{ token: "number", foreground: "098658" },
			{ token: "type", foreground: "267F99" },
			{ token: "function", foreground: "795E26" },
			{ token: "variable", foreground: "001080" },
			{ token: "constant", foreground: "0070C1" },
		],
		colors: {
			"editor.background": "#ffffff",
			"editor.foreground": "#333333",
			"editorLineNumber.foreground": "#999999",
			"editorLineNumber.activeForeground": "#333333",
			"editor.selectionBackground": "#add6ff",
			"editor.lineHighlightBackground": "#f7f7f7",
			"editorCursor.foreground": "#000000",
			"editorIndentGuide.background": "#d3d3d3",
			"editorIndentGuide.activeBackground": "#939393",
		},
	},
	"vercel-dark": {
		base: "vs-dark",
		inherit: false,
		rules: [
			{ token: "comment", foreground: "666666" },
			{ token: "keyword", foreground: "ffffff" },
			{ token: "string", foreground: "a3a3a3" },
			{ token: "number", foreground: "a3a3a3" },
			{ token: "type", foreground: "fafafa" },
			{ token: "function", foreground: "fafafa" },
			{ token: "variable", foreground: "e5e5e5" },
			{ token: "constant", foreground: "fafafa" },
		],
		colors: {
			"editor.background": "#000000",
			"editor.foreground": "#fafafa",
			"editorLineNumber.foreground": "#404040",
			"editorLineNumber.activeForeground": "#737373",
			"editor.selectionBackground": "#262626",
			"editor.lineHighlightBackground": "#0a0a0a",
			"editorCursor.foreground": "#fafafa",
			"editorIndentGuide.background": "#1a1a1a",
			"editorIndentGuide.activeBackground": "#333333",
		},
	},
	"vercel-light": {
		base: "vs",
		inherit: false,
		rules: [
			{ token: "comment", foreground: "a3a3a3" },
			{ token: "keyword", foreground: "171717" },
			{ token: "string", foreground: "525252" },
			{ token: "number", foreground: "525252" },
			{ token: "type", foreground: "171717" },
			{ token: "function", foreground: "171717" },
			{ token: "variable", foreground: "404040" },
			{ token: "constant", foreground: "171717" },
		],
		colors: {
			"editor.background": "#ffffff",
			"editor.foreground": "#171717",
			"editorLineNumber.foreground": "#d4d4d4",
			"editorLineNumber.activeForeground": "#a3a3a3",
			"editor.selectionBackground": "#e5e5e5",
			"editor.lineHighlightBackground": "#fafafa",
			"editorCursor.foreground": "#171717",
			"editorIndentGuide.background": "#e5e5e5",
			"editorIndentGuide.activeBackground": "#d4d4d4",
		},
	},
	"github-dark": {
		base: "vs-dark",
		inherit: false,
		rules: [
			{ token: "comment", foreground: "8B949E" },
			{ token: "keyword", foreground: "FF7B72" },
			{ token: "string", foreground: "A5D6FF" },
			{ token: "number", foreground: "79C0FF" },
			{ token: "type", foreground: "FFA657" },
			{ token: "function", foreground: "D2A8FF" },
			{ token: "variable", foreground: "FFA657" },
			{ token: "constant", foreground: "79C0FF" },
		],
		colors: {
			"editor.background": "#0d1117",
			"editor.foreground": "#e6edf3",
			"editorLineNumber.foreground": "#484F58",
			"editorLineNumber.activeForeground": "#8B949E",
			"editor.selectionBackground": "#264F78",
			"editor.lineHighlightBackground": "#161b22",
			"editorCursor.foreground": "#e6edf3",
			"editorIndentGuide.background": "#21262d",
			"editorIndentGuide.activeBackground": "#30363d",
		},
	},
	"github-light": {
		base: "vs",
		inherit: false,
		rules: [
			{ token: "comment", foreground: "6E7781" },
			{ token: "keyword", foreground: "CF222E" },
			{ token: "string", foreground: "0A3069" },
			{ token: "number", foreground: "0550AE" },
			{ token: "type", foreground: "953800" },
			{ token: "function", foreground: "8250DF" },
			{ token: "variable", foreground: "953800" },
			{ token: "constant", foreground: "0550AE" },
		],
		colors: {
			"editor.background": "#ffffff",
			"editor.foreground": "#1F2328",
			"editorLineNumber.foreground": "#8C959F",
			"editorLineNumber.activeForeground": "#24292F",
			"editor.selectionBackground": "#ddf4ff",
			"editor.lineHighlightBackground": "#f6f8fa",
			"editorCursor.foreground": "#1F2328",
			"editorIndentGuide.background": "#eaeef2",
			"editorIndentGuide.activeBackground": "#d0d7de",
		},
	},
	"monokai-pro": {
		base: "vs-dark",
		inherit: false,
		rules: [
			{ token: "comment", foreground: "727072" },
			{ token: "keyword", foreground: "FF6188" },
			{ token: "string", foreground: "FFD866" },
			{ token: "number", foreground: "AB9DF2" },
			{ token: "type", foreground: "78DCE8" },
			{ token: "function", foreground: "A9DC76" },
			{ token: "variable", foreground: "FCFCFA" },
			{ token: "constant", foreground: "AB9DF2" },
		],
		colors: {
			"editor.background": "#2d2a2e",
			"editor.foreground": "#fcfcfa",
			"editorLineNumber.foreground": "#5b595c",
			"editorLineNumber.activeForeground": "#939293",
			"editor.selectionBackground": "#5b595c",
			"editor.lineHighlightBackground": "#363437",
			"editorCursor.foreground": "#fcfcfa",
			"editorIndentGuide.background": "#403e41",
			"editorIndentGuide.activeBackground": "#5b595c",
		},
	},
	dracula: {
		base: "vs-dark",
		inherit: false,
		rules: [
			{ token: "comment", foreground: "6272A4" },
			{ token: "keyword", foreground: "FF79C6" },
			{ token: "string", foreground: "F1FA8C" },
			{ token: "number", foreground: "BD93F9" },
			{ token: "type", foreground: "8BE9FD" },
			{ token: "function", foreground: "50FA7B" },
			{ token: "variable", foreground: "F8F8F2" },
			{ token: "constant", foreground: "BD93F9" },
		],
		colors: {
			"editor.background": "#282A36",
			"editor.foreground": "#F8F8F2",
			"editorLineNumber.foreground": "#6272A4",
			"editorLineNumber.activeForeground": "#F8F8F2",
			"editor.selectionBackground": "#44475A",
			"editor.lineHighlightBackground": "#44475A",
			"editorCursor.foreground": "#F8F8F2",
			"editorIndentGuide.background": "#44475A",
			"editorIndentGuide.activeBackground": "#6272A4",
		},
	},
};

export function registerMonacoThemes(monaco: typeof Monaco) {
	for (const [name, theme] of Object.entries(monacoThemes)) {
		monaco.editor.defineTheme(name, theme);
	}
}
